name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Openwrt image
      env:
        NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
        USER_PASS: ${{ secrets.USER_PASS }}
      run: |
        curl -sL https://gist.githubusercontent.com/retyui/7115bb6acf151351a143ec8f96a7c561/raw/7099b9db76729dc5761da72aa8525f632d8875c9/debug-github-actions.sh | bash
        echo "++++++++++++++Before+++++++++++++"
        ls -lh .
        du -lh --max-depth=5
        chmod a+x ./build.sh && ./build.sh > ./build.log 2>&1
        cat ./build.log
        echo "++++++++++++++After+++++++++++++"
        ls -lh .
        du -lh --max-depth=5   
